services:
  db:
    container_name: db
    image: mysql
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
  server:
    depends_on:
      db:
        condition: service_healthy
    container_name: server
    env_file: .env
    build:
        context: .
        dockerfile: deploy/server/Dockerfile
        no_cache: true
    ports:
      - "${SERVER_PORT}:8080"
    restart: always
    networks:
      - backend


volumes:
    db: {}

networks:
  backend: {}