services:
  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
  server:
    depends_on:
      db:
        condition: service_healthy
    container_name: server
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_PORT
      - BOT_TOKEN
      - ONLY_MAKE_MIGRATIONS
      - NO_AUTH
      - ENVIRONMENT
    build:
        context: .
        dockerfile: deploy/server/Dockerfile
        no_cache: true
        args:
          - ENVIRONMENT
    ports:
      - "${SERVER_PORT}:8080"
    restart: always
    networks:
      - backend


volumes:
    db: {}

networks:
  backend: {}